import { relative } from "node:path";
import { StyleSheet } from "react-native";

export const mealsStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#030712" },
  scroll: { paddingHorizontal: 16 },
  header: { marginBottom: 16 },
  title: { color: "#F8FAFC", fontSize: 28, fontWeight: "800" },
  subtitle: { color: "#64748B", fontSize: 14, marginTop: 4 },
  tabBarWrapper: { backgroundColor: "transparent", paddingBottom: 12 },
  tabBar: { flexDirection: "row", padding: 4 },
  tab: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    borderRadius: 12,
    overflow: "hidden",
  },
  activeTab: {},
  tabText: { color: "#64748B", fontSize: 13, fontWeight: "600" },
  activeTabText: { color: "#FFFFFF" },
  // Foods tab
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 12,
  },
  searchInput: { flex: 1, color: "#F8FAFC", fontSize: 15 },
  empty: { alignItems: "center", paddingVertical: 60, gap: 12 },
  emptyTitle: { color: "#94A3B8", fontSize: 18, fontWeight: "600" },
  emptyText: {
    color: "#475569",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
  },
  foodCard: { padding: 14, marginBottom: 8 },
  foodRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  foodIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  foodInfo: { flex: 1 },
  foodName: { color: "#F8FAFC", fontSize: 15, fontWeight: "600" },
  foodMacros: { color: "#64748B", fontSize: 12, marginTop: 2 },
  foodActions: { flexDirection: "row", gap: 4 },
  foodActionBtn: { padding: 8 },
  // Meals library cards
  tplCard: { padding: 14, marginBottom: 10 },
  tplHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 10,
  },
  tplIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(124,58,237,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  tplInfo: { flex: 1 },
  tplName: { color: "#F8FAFC", fontSize: 15, fontWeight: "700" },
  tplMeta: { color: "#64748B", fontSize: 12, marginTop: 2 },
  tplFoodScroll: { marginBottom: 12 },
  tplFoodChip: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    marginRight: 6,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  tplFoodChipText: { color: "#94A3B8", fontSize: 12, fontWeight: "500" },
  tplActions: { flexDirection: "row", gap: 8 },
  tplEditBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  tplEditBtnText: { color: "#94A3B8", fontSize: 13, fontWeight: "600" },
  tplScheduleBtn: { flex: 2, borderRadius: 12, overflow: "hidden" },
  tplScheduleGrad: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
  },
  tplScheduleBtnText: { color: "#FFFFFF", fontSize: 13, fontWeight: "700" },
  // Modals
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.6)",
  },
  modalCard: { margin: 16, padding: 24, borderRadius: 24 },
  modalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  modalTitle: { color: "#F8FAFC", fontSize: 22, fontWeight: "800" },
  scheduleSubtitle: {
    color: "#A78BFA",
    fontSize: 13,
    fontWeight: "500",
    marginTop: 2,
  },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  input: {
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: "#F8FAFC",
    fontSize: 15,
    marginBottom: 12,
  },
  categoryScroll: { marginBottom: 16 },
  categoryChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  categoryChipActive: {
    backgroundColor: "rgba(124,58,237,0.25)",
    borderColor: "#7C3AED",
  },
  categoryChipText: { color: "#64748B", fontSize: 13, fontWeight: "500" },
  categoryChipTextActive: { color: "#A78BFA", fontWeight: "600" },
  sectionLabel: {
    color: "#94A3B8",
    fontSize: 11,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 8,
  },
  // Day chips (schedule modal)
  dayScroll: { marginBottom: 16 },
  dayChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    marginRight: 8,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  dayChipActive: {
    backgroundColor: "rgba(124,58,237,0.25)",
    borderColor: "#7C3AED",
  },
  dayChipText: { color: "#64748B", fontSize: 13, fontWeight: "500" },
  dayChipTextActive: { color: "#A78BFA", fontWeight: "600" },
  // Big modals (food picker inside)
  bigModalWrapper: { flex: 1, justifyContent: "flex-end" },
  bigModalCard: {
    margin: 16,
    padding: 24,
    borderRadius: 24,
    maxHeight: "90%",
  },
  modalBtn: { borderRadius: 14, overflow: "hidden", marginTop: 16 },
  modalBtnDisabled: { opacity: 0.7 },
  modalBtnGradient: {
    paddingVertical: 16,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
  },
  modalBtnText: { color: "#FFFFFF", fontSize: 16, fontWeight: "700" },
  modalBtnTextDisabled: { color: "#475569" },
  // Food picker (shared)
  foodPickerSection: { marginBottom: 4 },
  foodPickerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  foodPickerLabel: {
    color: "#94A3B8",
    fontSize: 13,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  foodPickerRequired: {
    color: "#EF4444",
    fontSize: 11,
    fontWeight: "500",
    textTransform: "none",
    letterSpacing: 0,
  },
  selectedBadge: {
    backgroundColor: "rgba(124,58,237,0.2)",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: "rgba(124,58,237,0.4)",
  },
  selectedBadgeText: { color: "#A78BFA", fontSize: 12, fontWeight: "600" },
  chipsScroll: { marginBottom: 10 },
  selectedChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(124,58,237,0.2)",
    borderWidth: 1,
    borderColor: "rgba(124,58,237,0.4)",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 8,
  },
  selectedChipText: { color: "#A78BFA", fontSize: 13, fontWeight: "500" },
  pickerSearchBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 8,
  },
  pickerSearchInput: { flex: 1, color: "#F8FAFC", fontSize: 13 },
  pickerList: { maxHeight: 180 },
  pickerEmpty: { alignItems: "center", paddingVertical: 24, gap: 8 },
  pickerEmptyText: {
    color: "#475569",
    fontSize: 13,
    textAlign: "center",
    lineHeight: 18,
  },
  pickerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    marginBottom: 4,
    backgroundColor: "rgba(255,255,255,0.03)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  pickerRowSelected: {
    backgroundColor: "rgba(124,58,237,0.12)",
    borderColor: "rgba(124,58,237,0.35)",
  },
  pickerFoodIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  pickerFoodInfo: { flex: 1 },
  pickerFoodName: { color: "#94A3B8", fontSize: 14, fontWeight: "500" },
  pickerFoodNameSelected: { color: "#F8FAFC", fontWeight: "600" },
  pickerFoodMeta: { color: "#475569", fontSize: 11, marginTop: 1 },
  checkCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  checkCircleSelected: { backgroundColor: "#7C3AED", borderColor: "#7C3AED" },
});
